version: '3'
services:
  client:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 8000:8000
    volumes:
      - ./client:/app
    depends_on:
      - api
  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
    depends_on:
      - db
    links:
      - db
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
  db:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: