apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: client
  replicas: 3
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: mern-app-nginx
          ports:
            - containerPort: 8000

          imagePullPolicy: Always