apiVersion: v1
kind: Service
metadata:
  name: node
  namespace: default
spec: 
  ports:
    - nodePort: 30001 # - 30000-302222
      port: 8000
      protocol: TCP
      targetPort: 8000

  selector:
    app: node
  type: NodePort