apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: default
spec: 
  ports:
    - nodePort: 30000 # - 30000-302222
      port: 8000
      protocol: TCP
      targetPort: 8000

  selector:
    app: api
  type: NodePort